version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: crm_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_pass
      POSTGRES_DB: crm_db
    ports:
      - "5433:5432"
    volumes:
      - crm_postgres_data:/var/lib/postgresql/data

volumes:
  crm_postgres_data:
